apiVersion: v2
name: kube-oidc-proxy
version: 1.1.0
description: Helm Chart for kube-oidc-proxy
keywords:
  - kubernetes
  - oidc
  - kube-apiserver
  - authentication
  - impersonation
home: https://telkomindonesia.github.io/kube-oidc-proxy-helm/
sources:
  - https://github.com/TelkomIndonesia/kube-oidc-proxy-helm
maintainers:
  - name: Mustapha Hadzi
    email: topahadzi@gmail.com
    url: https://github.com/topahadzi
  - name: I Putu Ariyasa
    email: rucciva@gmail.com
    url: https://github.com/rucciva
icon: https://kubernetes.io/images/favicon.png
appVersion: 1.0.3
