oidc:
  issuer: https://id.example.com/auth/realms/master
  clientID: kubernetes
  usernameClaim: preferred_username
  groupsClaim: groups
  usernamePrefix: "oidc:"
  groupsPrefix: "oidc:"
  requiredClaims: []

deployment:
  image:
    name: docker.io/tremolosecurity/kube-oidc-proxy:latest
    pullPolicy: Always
  replicas: 2
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  existingSecret: null
  podAnnotations: null

service:
  type: ClusterIP
  annotations: null
  externalTrafficPolicy: null
  loadBalancerIP: null
  ports:
    https: null

ingress:
  enabled: false
  annotations: null
  hosts:
    - api.kubernetes.example.com
  tlsSecret: null
