kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace | quote }}
