apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy: {{ toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      serviceAccountName: "{{ .Release.Name }}-{{ .Chart.Name }}"
      containers:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
          image: {{ .Values.deployment.image.name | quote }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | quote }}
          command:
            - kube-oidc-proxy
            - --secure-port=443
            - --tls-cert-file=/etc/oidc/tls/crt.pem
            - --tls-private-key-file=/etc/oidc/tls/key.pem
            - "--oidc-issuer-url={{ .Values.oidc.issuer }}"
            - "--oidc-client-id={{ .Values.oidc.clientID }}"
            {{- if .Values.oidc.clientSecret }}
            - "--oidc-client-secret={{.Values.oidc.clientSecret }}"
            {{- end }}
            - "--oidc-username-claim={{ .Values.oidc.usernameClaim }}"
            - "--oidc-username-prefix={{ .Values.oidc.usernamePrefix }}"
            - "--oidc-groups-claim={{ .Values.oidc.groupsClaim }}"
            - "--oidc-groups-prefix={{ .Values.oidc.groupsPrefix }}"
            {{- range .Values.oidc.requiredClaims }}
            - "--oidc-required-claim={{ . }}"
            {{- end }}
            {{- if .Values.verbosity }}
            - "--v={{ .Values.verbosity }}"
            {{- end }}
          volumeMounts:
            - name: kube-oidc-proxy-tls
              mountPath: /etc/oidc/tls
              readOnly: true
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 8080
            - name: https
              containerPort: 443
      volumes:
        - name: kube-oidc-proxy-tls
          secret:
            secretName: "{{ .Release.Name }}-{{ .Chart.Name }}"
            items:
              - key: tls.crt
                path: crt.pem
              - key: tls.key
                path: key.pem
