apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{- if .Values.service.annotations }}
  annotation: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
    - name: https
      port: 443
      targetPort: https
